### ISSUE TITLE
Audio360 Audio Engine license?

### ISSUE THREAD

**Issue by Neurrone** [facebookincubator/Audio360#1]
Hi,

What's the license for the actual [Audio360 Audio Engine SDK](https://facebookincubator.github.io/facebook-360-spatial-workstation/Documentation/SDK/Audio360_SDK_GettingStarted.html#sdk)? The closest license information I've found was for this repo, but not the actual engine itself.

**Comment by re-sounding** [comment]
The license is available on the download page under the legal tab: https://facebook360.fb.com/downloads/rendering-sdk-v1-6-0/
